# Generated by Django 6.0.6 on 2026-06-24 11:14

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import news.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Kategoriya')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=150, verbose_name='Lavozim')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skill nomi')),
                ('percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Foiz')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=250, unique=True, unique_for_date='publish', verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[news.models.validate_image_extension], verbose_name='Rasm')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Matn')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nashr vaqti')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Holat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Muallif')),
                ('body', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism')),
                ('surname', models.CharField(max_length=50, verbose_name='Familiya')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon')),
                ('about_me', models.TextField(verbose_name="O'zim haqimda")),
                ('works_completed', models.PositiveIntegerField(default=0, verbose_name='Bajarilgan ishlar')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Tajriba yillari')),
                ('total_clients', models.PositiveIntegerField(default=0, verbose_name='Mijozlar soni')),
                ('award_won', models.PositiveIntegerField(default=0, verbose_name='Yutuqlar')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_infos', to='news.jobs', verbose_name='Lavozim')),
                ('skills', models.ManyToManyField(related_name='user_infos', to='news.skills', verbose_name='Skills')),
            ],
            options={
                'verbose_name': "Foydalanuvchi ma'lumoti",
                'verbose_name_plural': "Foydalanuvchilar ma'lumotlari",
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='news_post_publish_fb80b2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='news_post_status_01ccc8_idx'),
        ),
    ]
